from enum import Enum

class EventType(Enum):
    HW_DATA_TRANSMISSION_ALTER = 1,
    RASP_UPDATE = 2,
    RASP_REMOVE = 3,
    MANAGE_USER_REFRESH = 4,
    MANAGE_FOOTAGES_REFRESH = 5,
    MANAGE_CAMERA_REFRESH = 6